# Generated by Django 4.1.3 on 2022-11-13 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tblClientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('factura', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tblInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.CharField(max_length=3)),
                ('nombre', models.CharField(max_length=50)),
                ('unidad', models.CharField(max_length=10)),
                ('precio', models.CharField(max_length=4)),
                ('cantidad', models.CharField(max_length=4)),
                ('existencias', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='tblProveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proveedor', models.CharField(max_length=3)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=8)),
                ('cantidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Compras.tblinventario')),
            ],
        ),
        migrations.CreateModel(
            name='tblPasteleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sucursal', models.CharField(max_length=3)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('cargo', models.CharField(max_length=6)),
                ('existencias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Compras.tblinventario')),
            ],
        ),
        migrations.CreateModel(
            name='tblEncargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_encargo', models.CharField(max_length=3)),
                ('anticipo', models.CharField(max_length=5)),
                ('fecha_encargo', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Compras.tblclientes')),
            ],
        ),
        migrations.CreateModel(
            name='tblEmpleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empleado', models.CharField(max_length=4)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Compras.tblpasteleria')),
            ],
        ),
    ]
