# Generated by Django 4.1.3 on 2022-11-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Compras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblpasteleria',
            name='cargo',
        ),
        migrations.AlterField(
            model_name='tblclientes',
            name='apellido',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tblclientes',
            name='factura',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tblclientes',
            name='id_cliente',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tblclientes',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tblempleados',
            name='apellido',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tblempleados',
            name='cargo',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='tblempleados',
            name='id_empleado',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='tblempleados',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tblencargos',
            name='anticipo',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='tblencargos',
            name='id_encargo',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='tblinventario',
            name='cantidad',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='tblinventario',
            name='existencias',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='tblinventario',
            name='id_producto',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='tblinventario',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tblinventario',
            name='precio',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='tblinventario',
            name='unidad',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='tblpasteleria',
            name='id_sucursal',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='tblpasteleria',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tblproveedores',
            name='apellido',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tblproveedores',
            name='id_proveedor',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='tblproveedores',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tblproveedores',
            name='telefono',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
